# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\";\n\x0cLayerWeights\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x05\"p\n\x0eWeightsRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x13\n\x0bnum_samples\x18\x03 \x01(\x05\x12\'\n\x06layers\x18\x04 \x03(\x0b\x32\x17.federated.LayerWeights\"]\n\x13GlobalModelResponse\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\'\n\x06layers\x18\x03 \x03(\x0b\x32\x17.federated.LayerWeights\"\"\n\rStatusRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"p\n\x0eStatusResponse\x12\x15\n\rcurrent_round\x18\x01 \x01(\x05\x12\x1a\n\x12\x63lients_registered\x18\x02 \x01(\x05\x12\x1a\n\x12\x63lients_this_round\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t2\x9f\x01\n\x11\x46\x65\x64\x65ratedLearning\x12H\n\x0bSendWeights\x12\x19.federated.WeightsRequest\x1a\x1e.federated.GlobalModelResponse\x12@\n\tGetStatus\x12\x18.federated.StatusRequest\x1a\x19.federated.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LAYERWEIGHTS']._serialized_start=30
  _globals['_LAYERWEIGHTS']._serialized_end=89
  _globals['_WEIGHTSREQUEST']._serialized_start=91
  _globals['_WEIGHTSREQUEST']._serialized_end=203
  _globals['_GLOBALMODELRESPONSE']._serialized_start=205
  _globals['_GLOBALMODELRESPONSE']._serialized_end=298
  _globals['_STATUSREQUEST']._serialized_start=300
  _globals['_STATUSREQUEST']._serialized_end=334
  _globals['_STATUSRESPONSE']._serialized_start=336
  _globals['_STATUSRESPONSE']._serialized_end=448
  _globals['_FEDERATEDLEARNING']._serialized_start=451
  _globals['_FEDERATEDLEARNING']._serialized_end=610
# @@protoc_insertion_point(module_scope)
